all:
	g++ -fopenmp -std=c++11 openmp.c -Wall -g -o openmp && ./openmp
	#gcc pthread.c -Wall -g -o pthread -lpthread && ./pthread

w:
	#gcc ex.c -Wall -g -o ex && ./ex

v:
	#gcc cache_simulation.c -Wall -g -o cach_sim && valgrind ./cach_sim

