all:
	gcc ex.c -g -o ex && clear && ./ex

w:
	gcc ex.c -Wall -g -o ex && ./ex

v:
	gcc cache_simulation.c -Wall -g -o cach_sim && valgrind ./cach_sim

c:
	gcc cache_simulation.c -Wall -g -o cach_sim && ./cach_sim


